# Base Image
FROM python:3.10

# 작업 디렉토리 설정
WORKDIR /app

# 필요한 패키지 설치
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# ffmpeg 설치 (오디오 변환에 필요)
RUN apt update && apt install -y ffmpeg

# Celery 실행을 위한 소스 코드 복사
COPY . .

# Celery Worker 실행
CMD ["celery", "-A", "tasks", "worker", "--loglevel=info"]
