version: "3.8"

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "25114:8000"
    env_file:
      - /home/ubuntu/.env
    environment:
      - IS_DOCKER=true
    depends_on:
      - rabbitmq

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: celery_worker
    env_file:
      - /home/ubuntu/.env
    environment:
      - IS_DOCKER=true
    depends_on:
      - rabbitmq

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP 프로토콜 포트
      - "15672:15672" # RabbitMQ 관리 UI 포트
